### ISSUE TITLE
Crashes after recording

### ISSUE THREAD

**Issue by jeetdholakia** [dennyabrain/InstagramTitles#1]
Hi,

I'm using the app on Pixel (8.0.0)

The app crashes after I click on record...

Here's the log if it might help...
```

10-23 18:10:29.750 26959-26959/dennymades.space.StitchAndroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: dennymades.space.StitchAndroid, PID: 26959
                                                                                java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                    at android.view.View$DeclaredOnClickListener.onClick(View.java:5336)
                                                                                    at android.view.View.performClick(View.java:6256)
                                                                                    at android.view.View$PerformClick.run(View.java:24697)
                                                                                    at android.os.Handler.handleCallback(Handler.java:789)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at android.view.View$DeclaredOnClickListener.onClick(View.java:5331)
                                                                                    at android.view.View.performClick(View.java:6256) 
                                                                                    at android.view.View$PerformClick.run(View.java:24697) 
                                                                                    at android.os.Handler.handleCallback(Handler.java:789) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                    at android.os.Looper.loop(Looper.java:164) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                    at android.graphics.Bitmap.createBitmap(Bitmap.java:718)
                                                                                    at dennymades.space.StitchAndroid.MainActivity.fabRecordClick(MainActivity.java:248)
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at android.view.View$DeclaredOnClickListener.onClick(View.java:5331) 
                                                                                    at android.view.View.performClick(View.java:6256) 
                                                                                    at android.view.View$PerformClick.run(View.java:24697) 
                                                                                    at android.os.Handler.handleCallback(Handler.java:789) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                    at android.os.Looper.loop(Looper.java:164) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by dennyabrain** [comment]
@jeetdholakia hey jeet,
I haven't been looking at this project in a long time so haven't had time to make some optimizations.
the reason for the crash is that, my app is looking for a bitmap file to overlay on the video before you start recording. this bitmap is mandatory (ideally, it should not be)
to get the app to record, you need to click on the 't' icon on the upper right corner and add some text on top of the video.
and then click on the 't' icon again and try recording now.
